//! A minimal `.npy` reader, enough to load f32 reference tensors.
//!
//! Written by hand rather than pulling in `ndarray-npy` for the same reason the
//! GGUF parser is hand-written: it is a small, stable, well-documented format,
//! and a dev-dependency that can read arbitrary numpy files is more surface than
//! this needs. We accept exactly one dtype (`<f4`) and refuse everything else,
//! because silently reinterpreting a float64 reference as float32 would be a
//! spectacularly confusing way to fail.
//!
//! Format: a 6-byte magic, two version bytes, a little-endian header length
//! (u16 for v1.x, u32 for v2+), then an ASCII Python dict literal, then raw data.

use alloc::string::{String, ToString};
use alloc::vec::Vec;

#[derive(Debug)]
pub struct Npy {
    pub shape: Vec<usize>,
    pub data: Vec<f32>,
}

impl Npy {
    pub fn n_elements(&self) -> usize {
        self.shape.iter().product()
    }
}

pub fn parse(bytes: &[u8]) -> Result<Npy, String> {
    if bytes.len() < 10 || &bytes[..6] != b"\x93NUMPY" {
        return Err("not a .npy file".to_string());
    }
    let major = bytes[6];
    let (header_len, header_start) = if major == 1 {
        (u16::from_le_bytes([bytes[8], bytes[9]]) as usize, 10)
    } else {
        let l = u32::from_le_bytes([bytes[8], bytes[9], bytes[10], bytes[11]]) as usize;
        (l, 12)
    };
    let header_end = header_start + header_len;
    if header_end > bytes.len() {
        return Err("truncated .npy header".to_string());
    }
    let header = core::str::from_utf8(&bytes[header_start..header_end])
        .map_err(|_| "non-UTF-8 .npy header".to_string())?;

    if !header.contains("'<f4'") && !header.contains("\"<f4\"") {
        return Err(alloc::format!(
            "reference tensors must be little-endian float32 ('<f4'); header says: {header}"
        ));
    }
    if header.contains("'fortran_order': True") {
        return Err(
            "fortran-ordered .npy is not supported; save with np.ascontiguousarray".to_string(),
        );
    }

    // shape is a Python tuple: "'shape': (3, 4)" or "(7,)" or "()" for a scalar.
    let open = header.find("'shape':").ok_or("no shape in .npy header")?;
    let lp = header[open..].find('(').ok_or("malformed shape")? + open;
    let rp = header[lp..].find(')').ok_or("malformed shape")? + lp;
    let mut shape = Vec::new();
    for part in header[lp + 1..rp].split(',') {
        let t = part.trim();
        if t.is_empty() {
            continue;
        }
        shape.push(
            t.parse::<usize>()
                .map_err(|_| alloc::format!("bad shape entry {t:?}"))?,
        );
    }
    if shape.is_empty() {
        shape.push(1); // 0-d array: treat as a single element
    }

    let n: usize = shape.iter().product();
    let body = &bytes[header_end..];
    if body.len() < n * 4 {
        return Err(alloc::format!(
            "truncated .npy body: shape {shape:?} needs {} bytes, found {}",
            n * 4,
            body.len()
        ));
    }
    let mut data = Vec::with_capacity(n);
    for c in body[..n * 4].as_chunks::<4>().0 {
        data.push(f32::from_le_bytes(*c));
    }
    Ok(Npy { shape, data })
}

/// Load a reference tensor from `tools/reference/`, or `None` if it is absent.
///
/// Absent is the normal state: the reference tensors are generated by a Python
/// script and deliberately not committed. Tests skip rather than fail.
#[cfg(feature = "std")]
pub fn load(relative: &str) -> Option<Npy> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../tools/reference")
        .join(relative);
    let bytes = std::fs::read(&path).ok()?;
    match parse(&bytes) {
        Ok(n) => Some(n),
        Err(e) => panic!("{}: {e}", path.display()),
    }
}
