#!/usr/bin/env python3
"""Generate the Unicode range tables the pre-tokenizer needs.

Qwen2's pre-tokenizer pattern uses `\\p{L}`, `\\p{N}` and `\\s`. Matching it
requires real Unicode classification -- an ASCII approximation silently produces
different token boundaries for any non-English text, which changes the token IDs,
which changes the output.

We cannot use the `regex` crate (not in the allowed dependency list, and it would
be the largest thing in the binary), so the classification comes from tables
generated here and binary-searched at runtime. Total cost is a few KB.

    python3 tools/gen_unicode_tables.py
"""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "crates/core/src/tokenizer/unicode_tables.rs"

MAX_CP = 0x110000

# \p{L} is the five letter categories; \p{N} is the three numeric ones.
LETTER_CATS = {"Lu", "Ll", "Lt", "Lm", "Lo"}
NUMBER_CATS = {"Nd", "Nl", "No"}

# The Unicode White_Space property. unicodedata does not expose it directly, so
# it is listed explicitly -- it is short and stable across versions.
WHITESPACE = set(
    [0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x20, 0x85, 0xA0, 0x1680]
    + list(range(0x2000, 0x200B))
    + [0x2028, 0x2029, 0x202F, 0x205F, 0x3000]
)


def ranges(pred) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    start = None
    for cp in range(MAX_CP):
        if pred(cp):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, MAX_CP - 1))
    return out


def emit(f, name: str, rs: list[tuple[int, int]], doc: str) -> None:
    f.write(f"/// {doc}\n")
    f.write(f"pub static {name}: &[(u32, u32)] = &[\n")
    for i in range(0, len(rs), 4):
        chunk = rs[i : i + 4]
        f.write("    " + " ".join(f"(0x{a:04X}, 0x{b:04X})," for a, b in chunk) + "\n")
    f.write("];\n\n")


def main() -> int:
    cat = [""] * MAX_CP
    for cp in range(MAX_CP):
        cat[cp] = unicodedata.category(chr(cp))

    letters = ranges(lambda cp: cat[cp] in LETTER_CATS)
    numbers = ranges(lambda cp: cat[cp] in NUMBER_CATS)
    spaces = ranges(lambda cp: cp in WHITESPACE)

    with OUT.open("w") as f:
        f.write("// @generated by tools/gen_unicode_tables.py -- do not edit by hand.\n")
        f.write(f"//\n// Unicode {unicodedata.unidata_version}. Sorted, non-overlapping,\n")
        f.write("// inclusive ranges; look them up with `in_ranges`.\n\n")
        emit(f, "LETTER", letters, r"Codepoints matching `\p{L}` (Lu, Ll, Lt, Lm, Lo).")
        emit(f, "NUMBER", numbers, r"Codepoints matching `\p{N}` (Nd, Nl, No).")
        emit(f, "WHITESPACE", spaces, r"Codepoints with the Unicode White_Space property.")

    n = len(letters) + len(numbers) + len(spaces)
    print(f"wrote {OUT}")
    print(f"  Unicode {unicodedata.unidata_version}")
    print(f"  LETTER      {len(letters):>4} ranges")
    print(f"  NUMBER      {len(numbers):>4} ranges")
    print(f"  WHITESPACE  {len(spaces):>4} ranges")
    print(f"  {n * 8} bytes of table data")
    return 0


if __name__ == "__main__":
    sys.exit(main())
