//! Op tests.
//!
//! Four layers:
//!
//! 1. **Analytic** -- values worked out by hand, or properties that pin the
//!    definition (rmsnorm does not centre; softmax is shift-invariant).
//! 2. **f64 oracle** -- every kernel against [`super::reference`], which measures
//!    real numerical error rather than just agreement between two f32 copies.
//! 3. **Property** -- proptest over the invariants that must hold for any input.
//! 4. **numpy reference tensors** -- generated by `tools/dump_reference_ops.py`,
//!    skipped when absent (they are not committed).
//!
//! The one thing none of these can settle is the RoPE pairing convention; see
//! the note on [`RopeKind`].

use super::reference as r;
use super::*;
use crate::testutil::npy;
use proptest::prelude::*;

// These must match the constants in tools/dump_reference_ops.py.
const REF_RMSNORM_EPS: f32 = 1e-6;
const REF_ROPE_FREQ_BASE: f32 = 1_000_000.0;
const REF_ROPE_HEAD_DIM: usize = 64;

/// Deterministic xorshift, so "random" inputs are reproducible without dragging
/// proptest into tests that just want a lot of numbers.
struct Rng(u64);

impl Rng {
    fn new(seed: u64) -> Self {
        Rng(seed | 1)
    }
    fn next_f32(&mut self) -> f32 {
        self.0 ^= self.0 << 13;
        self.0 ^= self.0 >> 7;
        self.0 ^= self.0 << 17;
        // `>> 40` leaves 24 bits, so 2^22 maps them onto [0, 4) and the shift
        // gives [-2, 2). Scale matters here: activations in a real forward pass
        // are O(1), and testing with values four orders of magnitude larger
        // turns every comparison into a cancellation-error measurement instead
        // of a correctness one.
        ((self.0 >> 40) as f32 / 4_194_304.0) - 2.0
    }
    fn vec(&mut self, n: usize) -> Vec<f32> {
        (0..n).map(|_| self.next_f32()).collect()
    }
}

/// Assert `|got - want| <= rel * |want| + abs`, elementwise.
///
/// The absolute term is not padding. A dot product's error scales with the
/// magnitude of its *intermediate* sums, not its result, so whenever
/// cancellation makes the result much smaller than the terms that produced it,
/// a purely relative tolerance measures the cancellation rather than the
/// implementation. `abs` is the accumulation budget; `rel` catches everything
/// that scales with the answer itself.
#[track_caller]
fn assert_close(got: &[f32], want: &[f32], rel: f32, abs: f32, what: &str) {
    assert_eq!(got.len(), want.len(), "{what}: length mismatch");
    let mut worst = 0.0f32;
    let mut worst_i = 0;
    for (i, (g, w)) in got.iter().zip(want).enumerate() {
        // Ratio of the actual error to its allowance; > 1 means a failure.
        let ratio = (g - w).abs() / (rel * w.abs() + abs);
        if ratio > worst {
            worst = ratio;
            worst_i = i;
        }
    }
    assert!(
        worst <= 1.0,
        "{what}: error {:e} at index {worst_i} exceeds allowance {:e} \
         (got {}, want {}; rel {rel:e}, abs {abs:e})",
        (got[worst_i] - want[worst_i]).abs(),
        rel * want[worst_i].abs() + abs,
        got[worst_i],
        want[worst_i]
    );
}

/// Worst absolute and relative error between two vectors.
fn worst_error(got: &[f32], want: &[f32]) -> (f32, f32) {
    let mut abs = 0.0f32;
    let mut rel = 0.0f32;
    for (g, w) in got.iter().zip(want) {
        abs = abs.max((g - w).abs());
        if w.abs() > 1e-6 {
            rel = rel.max((g - w).abs() / w.abs());
        }
    }
    (abs, rel)
}

/// Compare against a reference and print the achieved error.
///
/// Visible with `cargo test -- --nocapture`. These numbers are the baseline the
/// optimised kernels in step 9 have to be judged against: once SIMD reorders the
/// summations the results *will* move, and the question is whether they move
/// further from PyTorch than this.
#[track_caller]
fn check_against_reference(got: &[f32], want: &[f32], rel: f32, abs: f32, what: &str) {
    let (a, r) = worst_error(got, want);
    std::eprintln!(
        "  {what:<24} n={:<7} worst abs {a:.3e}  worst rel {r:.3e}",
        got.len()
    );
    assert_close(got, want, rel, abs, what);
}

// ============================================================ elementwise ==

#[test]
fn elementwise_basics() {
    let mut a = vec![1.0, 2.0, 3.0];
    add_assign(&mut a, &[10.0, 20.0, 30.0]);
    assert_eq!(a, vec![11.0, 22.0, 33.0]);

    mul_assign(&mut a, &[2.0, 0.5, 0.0]);
    assert_eq!(a, vec![22.0, 11.0, 0.0]);

    scale(&mut a, 0.5);
    assert_eq!(a, vec![11.0, 5.5, 0.0]);

    assert_eq!(dot(&[1.0, 2.0, 3.0], &[4.0, 5.0, 6.0]), 32.0);
    assert_eq!(dot(&[], &[]), 0.0);
}

#[test]
#[should_panic(expected = "length mismatch")]
fn elementwise_rejects_mismatched_lengths() {
    let mut a = vec![1.0, 2.0];
    add_assign(&mut a, &[1.0]);
}

// ================================================================= matmul ==

#[test]
fn matmul_hand_computed() {
    // lhs [2,3], rhs [2,3] -> out [2,2], with out[i,j] = dot(lhs_row_i, rhs_row_j).
    //   lhs = [[1,2,3],
    //          [4,5,6]]
    //   rhs = [[1,0,0],
    //          [0,1,0]]   (picks out component 0 and component 1)
    //   out = [[1,2],
    //          [4,5]]
    let lhs = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0];
    let rhs = [1.0, 0.0, 0.0, 0.0, 1.0, 0.0];
    let mut out = [0.0f32; 4];
    matmul_nt(&lhs, &rhs, &mut out, 2, 2, 3);
    assert_eq!(out, [1.0, 2.0, 4.0, 5.0]);
}

#[test]
fn matmul_against_identity_is_the_identity() {
    let mut rng = Rng::new(1);
    let (m, k) = (5, 8);
    let lhs = rng.vec(m * k);
    // rhs = I_k, so out[i,j] = lhs[i,j].
    let mut rhs = vec![0.0f32; k * k];
    for i in 0..k {
        rhs[i * k + i] = 1.0;
    }
    let mut out = vec![0.0f32; m * k];
    matmul_nt(&lhs, &rhs, &mut out, m, k, k);
    assert_eq!(out, lhs);
}

#[test]
fn matvec_agrees_with_matmul_of_one_row() {
    let mut rng = Rng::new(2);
    let (rows, cols) = (17, 33);
    let w = rng.vec(rows * cols);
    let x = rng.vec(cols);

    let mut via_matvec = vec![0.0f32; rows];
    matvec(&w, &x, &mut via_matvec, rows, cols);

    // matmul with m = 1: lhs is the single activation row, rhs is the weights.
    let mut via_matmul = vec![0.0f32; rows];
    matmul_nt(&x, &w, &mut via_matmul, 1, rows, cols);

    assert_eq!(
        via_matvec, via_matmul,
        "matvec must be exactly matmul at m=1"
    );
}

#[test]
fn matmul_and_matvec_match_the_f64_oracle() {
    let mut rng = Rng::new(3);
    let (m, n, k) = (6, 24, 128);
    let lhs = rng.vec(m * k);
    let rhs = rng.vec(n * k);

    let mut got = vec![0.0f32; m * n];
    let mut want = vec![0.0f32; m * n];
    matmul_nt(&lhs, &rhs, &mut got, m, n, k);
    r::matmul_nt(&lhs, &rhs, &mut want, m, n, k);
    // Sequential f32 accumulation over k=128 against f64: this is the yardstick
    // step 9's reordered summations get measured against.
    assert_close(&got, &want, 1e-5, 1e-5, "matmul_nt vs f64");

    let x = rng.vec(k);
    let mut got = vec![0.0f32; n];
    let mut want = vec![0.0f32; n];
    matvec(&rhs, &x, &mut got, n, k);
    r::matvec(&rhs, &x, &mut want, n, k);
    assert_close(&got, &want, 1e-5, 1e-5, "matvec vs f64");
}

// ================================================================ rmsnorm ==

#[test]
fn rmsnorm_hand_computed() {
    // x = [1,2,3,4], weight = 1, eps = 0
    //   mean(x^2) = (1 + 4 + 9 + 16) / 4 = 7.5
    //   rsqrt(7.5) = 1 / 2.7386128 = 0.36514837
    //   out = x * 0.36514837
    let x = [1.0, 2.0, 3.0, 4.0];
    let w = [1.0; 4];
    let mut out = [0.0f32; 4];
    rmsnorm(&x, &w, &mut out, 0.0);
    let s = 0.365_148_37f32;
    assert_close(&out, &[s, 2.0 * s, 3.0 * s, 4.0 * s], 1e-6, 1e-6, "rmsnorm");
}

#[test]
fn rmsnorm_does_not_centre_the_input() {
    // The distinguishing test against LayerNorm. A constant vector has zero
    // variance, so LayerNorm would map it to all-zeros. RMSNorm divides by the
    // RMS (which is 1 here) and returns it unchanged.
    let x = [1.0f32; 8];
    let w = [1.0f32; 8];
    let mut out = [0.0f32; 8];
    rmsnorm(&x, &w, &mut out, 0.0);
    assert_close(&out, &x, 1e-6, 1e-6, "constant vector must survive rmsnorm");
    assert!(
        out.iter().all(|v| *v != 0.0),
        "this is RMSNorm, not LayerNorm"
    );
}

#[test]
fn rmsnorm_output_has_unit_rms() {
    let mut rng = Rng::new(4);
    for n in [1usize, 7, 64, 896] {
        let x = rng.vec(n);
        let w = vec![1.0f32; n];
        let mut out = vec![0.0f32; n];
        rmsnorm(&x, &w, &mut out, 0.0);
        let rms = (out.iter().map(|v| v * v).sum::<f32>() / n as f32).sqrt();
        assert!((rms - 1.0).abs() < 1e-4, "n={n}: rms {rms}");
    }
}

#[test]
fn rmsnorm_applies_weight_elementwise() {
    let x = [2.0f32; 4]; // rms 2, so normalised to all-ones
    let w = [1.0, 2.0, 3.0, 4.0];
    let mut out = [0.0f32; 4];
    rmsnorm(&x, &w, &mut out, 0.0);
    assert_close(&out, &w, 1e-6, 1e-6, "weight passes straight through");
}

#[test]
fn rmsnorm_matches_the_f64_oracle() {
    let mut rng = Rng::new(5);
    let x = rng.vec(896);
    let w = rng.vec(896);
    let mut got = vec![0.0f32; 896];
    let mut want = vec![0.0f32; 896];
    rmsnorm(&x, &w, &mut got, 1e-6);
    r::rmsnorm(&x, &w, &mut want, 1e-6);
    assert_close(&got, &want, 1e-5, 1e-6, "rmsnorm vs f64");
}

// ================================================================ softmax ==

#[test]
fn softmax_hand_computed() {
    let mut x = [0.0f32; 4];
    softmax(&mut x);
    assert_close(&x, &[0.25; 4], 1e-6, 1e-6, "uniform");

    // [0, ln 2, ln 4] -> weights 1, 2, 4 -> /7
    let mut x = [
        0.0f32,
        core::f32::consts::LN_2,
        2.0 * core::f32::consts::LN_2,
    ];
    softmax(&mut x);
    assert_close(
        &x,
        &[1.0 / 7.0, 2.0 / 7.0, 4.0 / 7.0],
        1e-6,
        1e-6,
        "log weights",
    );
}

#[test]
fn softmax_survives_scores_that_would_overflow() {
    // exp(1000) is inf. Without the max subtraction this is inf/inf = NaN, and
    // one NaN in the residual stream ends the generation.
    let mut x = [1000.0f32, 1000.0, 1000.0];
    softmax(&mut x);
    assert_close(&x, &[1.0 / 3.0; 3], 1e-6, 1e-6, "large equal scores");
    assert!(x.iter().all(|v| v.is_finite()));

    let mut x = [-1000.0f32, -1000.0];
    softmax(&mut x);
    assert_close(&x, &[0.5, 0.5], 1e-6, 1e-6, "large negative scores");
}

#[test]
fn softmax_respects_negative_infinity_masking() {
    // This is how the causal mask reaches softmax.
    let mut x = [0.0f32, f32::NEG_INFINITY, f32::NEG_INFINITY];
    softmax(&mut x);
    assert_eq!(x, [1.0, 0.0, 0.0]);

    // A fully masked row must not produce NaN. Causal attention never generates
    // one, so reaching this means the mask is wrong -- zeros make that visible.
    let mut x = [f32::NEG_INFINITY; 3];
    softmax(&mut x);
    assert_eq!(x, [0.0; 3]);
}

#[test]
fn softmax_is_shift_invariant_and_normalised() {
    let mut rng = Rng::new(6);
    let base = rng.vec(128);
    let mut a = base.clone();
    softmax(&mut a);
    assert!((a.iter().sum::<f32>() - 1.0).abs() < 1e-5);
    assert!(a.iter().all(|v| *v >= 0.0));

    for shift in [-50.0f32, -1.0, 3.5, 80.0] {
        let mut b: Vec<f32> = base.iter().map(|v| v + shift).collect();
        softmax(&mut b);
        assert_close(&b, &a, 1e-4, 1e-6, &alloc::format!("shift {shift}"));
    }
}

#[test]
fn softmax_matches_the_f64_oracle() {
    let mut rng = Rng::new(7);
    let x = rng.vec(512);
    let mut got = x.clone();
    softmax(&mut got);
    let want = r::softmax(&x);
    assert_close(&got, &want, 1e-5, 1e-6, "softmax vs f64");
}

// =================================================== silu and swiglu ==

#[test]
fn silu_known_values() {
    assert_eq!(silu(0.0), 0.0);
    // silu(1) = 1 / (1 + e^-1) = 0.73105858
    assert!((silu(1.0) - 0.731_058_6).abs() < 1e-6);
    // silu(-1) = -1 / (1 + e) = -0.26894143
    assert!((silu(-1.0) + 0.268_941_43).abs() < 1e-6);
    // Large positive: silu(x) -> x
    assert!((silu(30.0) - 30.0).abs() < 1e-4);
}

#[test]
fn silu_is_finite_at_both_extremes() {
    // exp(-x) overflows to inf for x < -88, giving x/inf = -0.0 rather than NaN.
    // That is the correct limit, and it is why no branch is needed.
    for x in [-1e30f32, -1e10, -200.0, -89.0, -88.0, 88.0, 1e10, 1e30] {
        let y = silu(x);
        assert!(y.is_finite(), "silu({x}) = {y}");
    }
    assert_eq!(silu(-1e30), -0.0);
    assert_eq!(silu(1e30), 1e30);
}

#[test]
fn silu_matches_the_f64_oracle() {
    let mut rng = Rng::new(8);
    let x = rng.vec(1024);
    let got: Vec<f32> = x.iter().map(|v| silu(*v)).collect();
    let want: Vec<f32> = x.iter().map(|v| r::silu(*v)).collect();
    assert_close(&got, &want, 1e-5, 1e-6, "silu vs f64");

    let mut inplace = x.clone();
    silu_inplace(&mut inplace);
    assert_eq!(inplace, got, "silu_inplace must match the scalar form");
}

#[test]
fn swiglu_is_silu_of_gate_times_up() {
    let mut rng = Rng::new(9);
    let gate = rng.vec(256);
    let up = rng.vec(256);
    let mut got = gate.clone();
    swiglu(&mut got, &up);
    let want = r::swiglu(&gate, &up);
    assert_close(&got, &want, 1e-5, 1e-6, "swiglu vs f64");

    // And explicitly: it is the gate that gets the nonlinearity, not the up.
    let mut manual = gate.clone();
    silu_inplace(&mut manual);
    mul_assign(&mut manual, &up);
    assert_eq!(got, manual);
}

// =================================================================== rope ==

#[test]
fn rope_at_position_zero_is_the_identity() {
    // Every angle is 0, so cos = 1 and sin = 0.
    let t = RopeTable::new(64, 64, 8, 1e6, RopeKind::SplitHalf);
    let mut rng = Rng::new(10);
    let x = rng.vec(64);
    let mut y = x.clone();
    t.apply_head(&mut y, 0);
    assert_eq!(y, x, "position 0 must not rotate anything");
}

#[test]
fn rope_hand_computed_both_conventions() {
    // head_dim = rope_dim = 4, freq_base = 10000, position 1.
    //   theta_0 = 10000^(-0/4) = 1       angle 1.0
    //   theta_1 = 10000^(-2/4) = 1/100   angle 0.01
    // x = [1, 0, 0, 1]
    //
    // split-half pairs (x[0],x[2]) and (x[1],x[3]):
    //   plane 0: (1,0) -> (cos1, sin1)
    //   plane 1: (0,1) -> (-sin.01, cos.01)
    //   out = [cos1, -sin.01, sin1, cos.01]
    //
    // adjacent pairs (x[0],x[1]) and (x[2],x[3]):
    //   plane 0: (1,0) -> (cos1, sin1)
    //   plane 1: (0,1) -> (-sin.01, cos.01)
    //   out = [cos1, sin1, -sin.01, cos.01]
    let (c1, s1) = (0.540_302_3f32, 0.841_470_96f32);
    let (c01, s01) = (0.999_95f32, 0.009_999_833f32);
    let x = [1.0f32, 0.0, 0.0, 1.0];

    let mut y = x;
    RopeTable::new(4, 4, 4, 10_000.0, RopeKind::SplitHalf).apply_head(&mut y, 1);
    assert_close(&y, &[c1, -s01, s1, c01], 1e-5, 1e-6, "split-half");

    let mut y = x;
    RopeTable::new(4, 4, 4, 10_000.0, RopeKind::Adjacent).apply_head(&mut y, 1);
    assert_close(&y, &[c1, s1, -s01, c01], 1e-5, 1e-6, "adjacent");
}

#[test]
fn the_two_conventions_actually_differ() {
    // If this ever passes trivially, the enum has stopped meaning anything and
    // the convention trap is back.
    let mut rng = Rng::new(11);
    let x = rng.vec(64);
    let mut a = x.clone();
    let mut b = x.clone();
    RopeTable::new(64, 64, 8, 1e6, RopeKind::SplitHalf).apply_head(&mut a, 3);
    RopeTable::new(64, 64, 8, 1e6, RopeKind::Adjacent).apply_head(&mut b, 3);
    assert_ne!(a, b, "the two pairings must produce different vectors");
}

#[test]
fn rope_preserves_the_norm() {
    // A rotation is orthogonal, so the length of the whole vector is unchanged.
    // This holds for either convention -- which is exactly why it cannot tell
    // them apart, and why the pairing needs a reference comparison.
    let mut rng = Rng::new(12);
    for kind in [RopeKind::SplitHalf, RopeKind::Adjacent] {
        let t = RopeTable::new(64, 64, 128, 1e6, kind);
        for pos in [0usize, 1, 7, 63, 127] {
            let x = rng.vec(64);
            let before: f32 = x.iter().map(|v| v * v).sum();
            let mut y = x.clone();
            t.apply_head(&mut y, pos);
            let after: f32 = y.iter().map(|v| v * v).sum();
            assert!(
                (before - after).abs() / before < 1e-5,
                "{kind:?} at pos {pos}: {before} -> {after}"
            );
        }
    }
}

#[test]
fn rope_leaves_unrotated_dimensions_alone() {
    // rope_dim < head_dim: the tail must pass through untouched.
    let t = RopeTable::new(8, 4, 4, 10_000.0, RopeKind::SplitHalf);
    let x = [1.0f32, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0];
    let mut y = x;
    t.apply_head(&mut y, 2);
    assert_eq!(&y[4..], &x[4..], "components >= rope_dim must not move");
    assert_ne!(&y[..4], &x[..4], "components < rope_dim must move");
}

#[test]
fn rope_matches_the_complex_number_oracle() {
    let mut rng = Rng::new(13);
    for (kind, split) in [(RopeKind::SplitHalf, true), (RopeKind::Adjacent, false)] {
        let t = RopeTable::new(64, 64, 64, 1e6, kind);
        for pos in [0usize, 1, 5, 33, 63] {
            let x = rng.vec(64);
            let mut got = x.clone();
            t.apply_head(&mut got, pos);
            let want = r::rope_head(&x, pos, 64, 64, 1e6, split);
            assert_close(
                &got,
                &want,
                1e-4,
                1e-6,
                &alloc::format!("{kind:?} pos {pos}"),
            );
        }
    }
}

#[test]
fn rope_projection_rotates_each_head_independently() {
    let mut rng = Rng::new(14);
    let (n_heads, head_dim) = (14, 64);
    let t = RopeTable::new(head_dim, head_dim, 16, 1e6, RopeKind::SplitHalf);
    let x = rng.vec(n_heads * head_dim);

    let mut whole = x.clone();
    t.apply_projection(&mut whole, n_heads, 5);

    for h in 0..n_heads {
        let mut one = x[h * head_dim..(h + 1) * head_dim].to_vec();
        t.apply_head(&mut one, 5);
        assert_eq!(
            &whole[h * head_dim..(h + 1) * head_dim],
            &one[..],
            "head {h}"
        );
    }
}

#[test]
#[should_panic(expected = "exactly one head")]
fn rope_rejects_a_whole_projection_passed_as_one_head() {
    // Rotating across a head boundary is fluent-but-wrong, so it is a hard error.
    let t = RopeTable::new(64, 64, 8, 1e6, RopeKind::SplitHalf);
    let mut x = vec![0.0f32; 64 * 14];
    t.apply_head(&mut x, 0);
}

#[test]
fn rope_table_reports_its_memory() {
    // 32768 positions x 32 planes x 2 tables x 4 bytes = 8 MiB, which is why the
    // engine sizes this to max_seq rather than context_length.
    let t = RopeTable::new(64, 64, 32768, 1e6, RopeKind::SplitHalf);
    assert_eq!(t.byte_len(), 8 * 1024 * 1024);
    assert_eq!(t.n_planes(), 32);
}

// =============================================================== property ==

proptest! {
    #[test]
    fn softmax_always_sums_to_one(xs in proptest::collection::vec(-50.0f32..50.0, 1..200)) {
        let mut v = xs.clone();
        softmax(&mut v);
        let sum: f32 = v.iter().sum();
        prop_assert!((sum - 1.0).abs() < 1e-4, "sum {sum}");
        prop_assert!(v.iter().all(|p| (0.0..=1.0).contains(p)));
        // Softmax is monotone: the largest score keeps the largest probability.
        let argmax_in = xs.iter().enumerate().fold((0, f32::NEG_INFINITY), |a, (i, &x)| if x > a.1 { (i, x) } else { a }).0;
        let argmax_out = v.iter().enumerate().fold((0, f32::NEG_INFINITY), |a, (i, &x)| if x > a.1 { (i, x) } else { a }).0;
        prop_assert_eq!(argmax_in, argmax_out, "softmax must preserve the argmax");
    }

    #[test]
    fn rmsnorm_always_produces_unit_rms(xs in proptest::collection::vec(-100.0f32..100.0, 1..300)) {
        // Only meaningful when the input is not vanishingly small, since eps
        // deliberately dominates there.
        let ss: f32 = xs.iter().map(|v| v * v).sum::<f32>() / xs.len() as f32;
        prop_assume!(ss > 1e-3);
        let w = vec![1.0f32; xs.len()];
        let mut out = vec![0.0f32; xs.len()];
        rmsnorm(&xs, &w, &mut out, 1e-6);
        let rms = (out.iter().map(|v| v * v).sum::<f32>() / xs.len() as f32).sqrt();
        prop_assert!((rms - 1.0).abs() < 1e-3, "rms {rms}");
    }

    #[test]
    fn rope_is_a_rotation_for_any_position(
        xs in proptest::collection::vec(-10.0f32..10.0, 16),
        pos in 0usize..64,
    ) {
        let t = RopeTable::new(16, 16, 64, 1e6, RopeKind::SplitHalf);
        let before: f32 = xs.iter().map(|v| v * v).sum();
        prop_assume!(before > 1e-6);
        let mut y = xs.clone();
        t.apply_head(&mut y, pos);
        let after: f32 = y.iter().map(|v| v * v).sum();
        prop_assert!((before - after).abs() / before < 1e-4);
    }

    #[test]
    fn matvec_is_linear(
        w in proptest::collection::vec(-2.0f32..2.0, 4 * 8),
        x in proptest::collection::vec(-2.0f32..2.0, 8),
        s in -3.0f32..3.0,
    ) {
        let mut a = vec![0.0f32; 4];
        matvec(&w, &x, &mut a, 4, 8);

        let scaled: Vec<f32> = x.iter().map(|v| v * s).collect();
        let mut b = vec![0.0f32; 4];
        matvec(&w, &scaled, &mut b, 4, 8);

        for i in 0..4 {
            let want = a[i] * s;
            prop_assert!((b[i] - want).abs() <= 1e-4 * want.abs().max(1.0));
        }
    }
}

// ====================================================== numpy reference ==

/// Reference tensors are generated by `tools/dump_reference_ops.py` and are not
/// committed. When they are absent every case below is skipped, and the test
/// says so rather than passing silently.
#[test]
fn matches_numpy_reference_tensors() {
    let Some(x) = npy::load("ops/rmsnorm_x.npy") else {
        eprintln!(
            "note: no reference tensors; run\n  python3 tools/dump_reference_ops.py\n  \
             to generate them (needs numpy only)"
        );
        return;
    };

    // --- rmsnorm: [rows, d] against a [d] weight -------------------------
    let w = npy::load("ops/rmsnorm_w.npy").expect("rmsnorm_w.npy");
    let want = npy::load("ops/rmsnorm_out.npy").expect("rmsnorm_out.npy");
    let d = *x.shape.last().unwrap();
    let rows = x.n_elements() / d;
    let mut got = vec![0.0f32; x.n_elements()];
    for i in 0..rows {
        rmsnorm(
            &x.data[i * d..(i + 1) * d],
            &w.data,
            &mut got[i * d..(i + 1) * d],
            REF_RMSNORM_EPS,
        );
    }
    check_against_reference(&got, &want.data, 1e-4, 1e-6, "rmsnorm vs numpy");

    // --- softmax: independently over each row ----------------------------
    let x = npy::load("ops/softmax_x.npy").expect("softmax_x.npy");
    let want = npy::load("ops/softmax_out.npy").expect("softmax_out.npy");
    let d = *x.shape.last().unwrap();
    let mut got = x.data.clone();
    for row in got.chunks_exact_mut(d) {
        softmax(row);
    }
    check_against_reference(&got, &want.data, 1e-4, 1e-6, "softmax vs numpy");

    // --- silu ------------------------------------------------------------
    let x = npy::load("ops/silu_x.npy").expect("silu_x.npy");
    let want = npy::load("ops/silu_out.npy").expect("silu_out.npy");
    let got: Vec<f32> = x.data.iter().map(|v| silu(*v)).collect();
    check_against_reference(&got, &want.data, 1e-4, 1e-6, "silu vs numpy");

    // --- swiglu ----------------------------------------------------------
    let gate = npy::load("ops/swiglu_gate.npy").expect("swiglu_gate.npy");
    let up = npy::load("ops/swiglu_up.npy").expect("swiglu_up.npy");
    let want = npy::load("ops/swiglu_out.npy").expect("swiglu_out.npy");
    let mut got = gate.data.clone();
    swiglu(&mut got, &up.data);
    check_against_reference(&got, &want.data, 1e-4, 1e-6, "swiglu vs numpy");

    // --- matmul: lhs [m,k] x rhs [n,k] -> [m,n] --------------------------
    let lhs = npy::load("ops/matmul_lhs.npy").expect("matmul_lhs.npy");
    let rhs = npy::load("ops/matmul_rhs.npy").expect("matmul_rhs.npy");
    let want = npy::load("ops/matmul_out.npy").expect("matmul_out.npy");
    let (m, k) = (lhs.shape[0], lhs.shape[1]);
    let n = rhs.shape[0];
    assert_eq!(rhs.shape[1], k, "matmul reference shapes disagree");
    let mut got = vec![0.0f32; m * n];
    matmul_nt(&lhs.data, &rhs.data, &mut got, m, n, k);
    check_against_reference(&got, &want.data, 1e-4, 1e-5, "matmul vs numpy");

    // --- rope: one row per position, both conventions --------------------
    let x = npy::load("ops/rope_x.npy").expect("rope_x.npy");
    let hd = REF_ROPE_HEAD_DIM;
    let n_pos = x.n_elements() / hd;
    for (file, kind) in [
        ("ops/rope_split_half.npy", RopeKind::SplitHalf),
        ("ops/rope_adjacent.npy", RopeKind::Adjacent),
    ] {
        let want = npy::load(file).unwrap_or_else(|| panic!("{file}"));
        let t = RopeTable::new(hd, hd, n_pos, REF_ROPE_FREQ_BASE, kind);
        let mut got = x.data.clone();
        for p in 0..n_pos {
            t.apply_head(&mut got[p * hd..(p + 1) * hd], p);
        }
        check_against_reference(
            &got,
            &want.data,
            1e-4,
            1e-6,
            &alloc::format!("rope {kind:?} vs numpy"),
        );
    }
}
